# *******************************************************************************
# Copyright (c) 2025 Contributors to the Eclipse Foundation
#
# See the NOTICE file(s) distributed with this work for additional
# information regarding copyright ownership.
#
# This program and the accompanying materials are made available under the
# terms of the Apache License Version 2.0 which is available at
# https://www.apache.org/licenses/LICENSE-2.0
#
# SPDX-License-Identifier: Apache-2.0
# *******************************************************************************

# ╓                                                          ╖
# ║ Some portions generated by Claude                        ║
# ╙                                                          ╜

import pytest
from src.registry_manager.bazel_wrapper import parse_MODULE_file_content


class TestModuleFileParsing:
    """Test parsing MODULE.bazel content."""

    def test_parse_complete_module_file(self):
        content = 'module(name="score_demo", version="1.2.3", compatibility_level=2)'
        parsed = parse_MODULE_file_content(content)
        assert str(parsed.version) == "1.2.3"
        assert parsed.comp_level == 2
        assert parsed.major_version == 1  # major version is first digit of version

    def test_parse_minimal_module_file(self):
        content = 'module(name="score_demo")'
        parsed = parse_MODULE_file_content(content)
        assert parsed.version is None
        assert parsed.comp_level is None
        assert parsed.major_version is None

    def test_parse_ignores_bazel_dep_version(self):
        content = """
            module(
                name = "score_docs_as_code",
                version = "2.0.0",
                )
            bazel_dep(name = "rules_python", version = "0.1.0)"'
        """
        parsed = parse_MODULE_file_content(content)
        assert str(parsed.version) == "2.0.0"

    def test_parse_only_bazel_dep_present(self):
        content = 'bazel_dep(name = "rules_python", version = "0.1.0")'

        with pytest.raises(
            ValueError, match=r"No 'module' declaration found in MODULE.bazel"
        ):
            parse_MODULE_file_content(content)

    def test_parse_module_without_version(self):
        content = """
            module(name = "my_project")

            bazel_dep(name = "some_dep", version = "5.0.0")
            """
        parsed = parse_MODULE_file_content(content)
        assert 'version = ""' in parsed.content
        assert "compatibility_level = 0" in parsed.content
        assert parsed.version is None

    def test_parse_minimal_module_declaration(self):
        content = 'module(name="score_demo")\nbazel_dep("platform", version="1.0.0)"'
        parsed = parse_MODULE_file_content(content)
        assert parsed.version is None
        assert parsed.comp_level is None
        assert parsed.major_version is None

    def test_parse_module_file_content_preserved(self):
        content = 'module(name="test", version="1.0.0", compatibility_level=1)\nbazel_dep(...)'
        parsed = parse_MODULE_file_content(content)
        assert parsed.content == content
