# *******************************************************************************
# Copyright (c) 2025 Contributors to the Eclipse Foundation
#
# See the NOTICE file(s) distributed with this work for additional
# information regarding copyright ownership.
#
# This program and the accompanying materials are made available under the
# terms of the Apache License Version 2.0 which is available at
# https://www.apache.org/licenses/LICENSE-2.0
#
# SPDX-License-Identifier: Apache-2.0
# *******************************************************************************

# ╓                                                          ╖
# ║ Some portions generated by Claude                        ║
# ╙                                                          ╜

import json
import os
from collections.abc import Callable
from pathlib import Path
from unittest.mock import patch

import pytest
from src.registry_manager.bazel_wrapper import (
    ModuleUpdateRunner,
    parse_MODULE_file_content,
)

from tests.conftest import make_update_info


class TestFileGeneration:
    """Test generating registry files."""

    def test_generates_source_json(
        self,
        basic_registry_setup: Callable[..., None],
    ) -> None:
        basic_registry_setup()
        os.chdir("/")

        # Setup: module score_demo with org/repo, release version 1.0.0
        version = "1.0.0"
        org_repo = "org/repo"
        update_info = make_update_info(version=version)
        # Note: make_update_info defaults to org/repo, but we're being explicit here

        # Mock sha256 calculation to return a test value
        mock_sha256 = "sha256-test"
        runner = ModuleUpdateRunner(update_info)
        with patch(
            "src.registry_manager.bazel_wrapper.sha256_from_url",
            return_value=mock_sha256,
        ):
            runner.generate_files()

        # Verify source.json contains the correct URL and integrity
        source_file = Path("/modules/score_demo/1.0.0/source.json")
        assert source_file.exists()
        source = json.loads(source_file.read_text())
        assert (
            source["url"]
            == f"https://github.com/{org_repo}/archive/refs/tags/v{version}.tar.gz"
        )
        assert source["integrity"] == mock_sha256

    def test_generates_module_file(
        self,
        basic_registry_setup: Callable[..., None],
    ) -> None:
        basic_registry_setup()
        os.chdir("/")

        # When version and comp_level match, no patching is needed
        version = "1.0.0"
        comp_level = 1  # Defaults to first digit of version
        update_info = make_update_info(version=version)

        runner = ModuleUpdateRunner(update_info)
        with patch(
            "src.registry_manager.bazel_wrapper.sha256_from_url",
            return_value="sha256-test",
        ):
            runner.generate_files()

        # Verify MODULE.bazel is created with correct version and compatibility
        module_file = Path("/modules/score_demo/1.0.0/MODULE.bazel")
        assert module_file.exists()
        expected = f'module(version="{version}", compatibility_level={comp_level})'
        assert expected in module_file.read_text()

    @pytest.mark.parametrize(
        (
            "release_version",
            "module_version",
            "module_comp_level",
            "expected_comp_level",
        ),
        [
            # Case 1: Release is v2.0.0, but MODULE.bazel says
            # version="1.0.0". Patch needed to change version from
            # 1.0.0 to 2.0.0, and comp_level from 1 to 2
            ("2.0.0", "1.0.0", 1, 2),
            # Case 2: Release is v3.0.0, MODULE.bazel says
            # version="3.0.0" but comp_level=1. Patch needed to
            # change comp_level from 1 to 3 (should match major)
            ("3.0.0", "3.0.0", 1, 3),
            # Case 3: Both mismatches
            ("2.3.4", "1.5.0", 1, 2),
            # Case 4: Release is "ABC", MODULE.bazel says version="1.0.0".
            # Patch needed to change version to "ABC". Compatibility
            # level remains as-is, as it cannot be derived from non-semver.
            ("ABC", "1.0.0", 42, 42),
        ],
    )
    def test_creates_patch_when_mismatch(
        self,
        basic_registry_setup: Callable[..., None],
        release_version: str,
        module_version: str,
        module_comp_level: int,
        expected_comp_level: int,
    ) -> None:
        """Test patches for MODULE.bazel version/comp_level mismatches."""
        basic_registry_setup()
        os.chdir("/")

        # Setup: GitHub release is at release_version, but the
        # MODULE.bazel file in that release declares module_version
        # with module_comp_level
        update_info = make_update_info(
            version=release_version,  # What GitHub says
            module_version=module_version,  # What MODULE.bazel says
            comp_level=module_comp_level,  # What MODULE.bazel has
        )

        runner = ModuleUpdateRunner(update_info)
        with patch(
            "src.registry_manager.bazel_wrapper.sha256_from_url",
            return_value="sha256-test",
        ):
            runner.generate_files()

        # When there's a mismatch, a patch should be created
        patches_dir = Path(f"/modules/score_demo/{release_version}/patches")
        assert patches_dir.exists()

        patch_file = patches_dir / "module_dot_bazel_version.patch"
        assert patch_file.exists()

        # Patch should correct the version and compatibility_level
        patch_content = patch_file.read_text()
        assert f'version="{release_version}"' in patch_content
        assert f"compatibility_level={expected_comp_level}" in patch_content

        # MODULE.bazel file should reflect the patched version/comp_level, not
        # the original ones!
        mod = Path(f"/modules/score_demo/{release_version}/MODULE.bazel").read_text()
        assert release_version in mod
        if module_version != release_version:
            assert module_version not in mod

    def test_no_patch_when_versions_match(
        self,
        basic_registry_setup: Callable[..., None],
    ) -> None:
        basic_registry_setup()
        os.chdir("/")

        # When release version matches MODULE.bazel version and
        # comp_level is correct, no patch should be generated
        version = "1.0.0"
        update_info = make_update_info(
            version=version,
            module_version=version,  # Same as release
            comp_level=1,  # Matches major version
        )

        runner = ModuleUpdateRunner(update_info)
        with patch(
            "src.registry_manager.bazel_wrapper.sha256_from_url",
            return_value="sha256-test",
        ):
            runner.generate_files()

        # Verify no patches section in source.json
        source_path = Path("/modules/score_demo/1.0.0/source.json")
        source = json.loads(source_path.read_text())
        assert "patches" not in source

    def test_appends_version_with_semver_sorting(
        self,
        basic_registry_setup: Callable[..., None],
    ) -> None:
        # Setup: metadata.json has versions 1.0.9 and 1.0.10
        # Note: 1.0.10 > 1.0.9 in semver (not lexical where "10" < "9")
        existing = ["1.0.9", "1.0.10"]
        basic_registry_setup(versions=existing)
        os.chdir("/")

        # Add new version 1.0.11
        new_version = "1.0.11"
        update_info = make_update_info(
            version=new_version,
            existing_versions=existing,
        )

        runner = ModuleUpdateRunner(update_info)
        with patch(
            "src.registry_manager.bazel_wrapper.sha256_from_url",
            return_value="sha256-test",
        ):
            runner.generate_files()

        # Verify versions are sorted descending by semver (newest first)
        metadata_path = Path("/modules/score_demo/metadata.json")
        metadata = json.loads(metadata_path.read_text())
        generated_versions = metadata["versions"]
        expected_versions = ["1.0.11", "1.0.10", "1.0.9"]
        assert generated_versions == expected_versions

    def test_patch_ignores_bazel_dep_versions(
        self,
        basic_registry_setup: Callable[..., None],
    ) -> None:
        """Test that patching only affects module() version, not bazel_dep() versions."""
        basic_registry_setup()
        os.chdir("/")

        # MODULE.bazel has version="1.0.0" in module(), but also has bazel_dep
        # with version="0.25.0". Release version is 2.0.0.
        release_version = "2.0.0"

        # Create a custom ModuleFileContent with bazel_dep entries
        module_content_str = """module(
    name = "score_demo",
    version = "1.0.0",
    compatibility_level = 1,
)

bazel_dep(name = "rules_python", version = "0.25.0")
bazel_dep(name = "rules_go", version = "0.41.0")
"""

        # Parse the module content to extract version and comp_level from module() only
        mod_file = parse_MODULE_file_content(module_content_str)

        # Verify parser correctly extracted from module() and ignored bazel_dep
        assert str(mod_file.version) == "1.0.0"  # Not "0.25.0" from bazel_dep
        assert mod_file.comp_level == 1

        update_info = make_update_info(version=release_version)
        update_info.mod_file = mod_file

        runner = ModuleUpdateRunner(update_info)
        with patch(
            "src.registry_manager.bazel_wrapper.sha256_from_url",
            return_value="sha256-test",
        ):
            runner.generate_files()

        # Verify patch was created
        patch_file = Path(
            f"/modules/score_demo/{release_version}/patches/module_dot_bazel_version.patch"
        )
        assert patch_file.exists()

        # Verify patched MODULE.bazel has correct module() version
        module_file = Path(f"/modules/score_demo/{release_version}/MODULE.bazel")
        module_content = module_file.read_text()

        # Should update module() version to 2.0.0 and comp_level to 2
        assert (
            'version = "2.0.0"' in module_content or 'version="2.0.0"' in module_content
        )
        assert (
            "compatibility_level = 2" in module_content
            or "compatibility_level=2" in module_content
        )

        # Should NOT touch bazel_dep versions
        assert 'bazel_dep(name = "rules_python", version = "0.25.0")' in module_content
        assert 'bazel_dep(name = "rules_go", version = "0.41.0")' in module_content

    def test_patch_adds_version_to_module_without_version(
        self,
        basic_registry_setup: Callable[..., None],
    ) -> None:
        """Ensure our patch changes the right version if none is in module.bazel"""
        basic_registry_setup()
        os.chdir("/")

        release_version = "1.5.0"

        module_content_str = """module(
    name = "score_demo",
)

bazel_dep(name = "rules_python", version = "0.26.0")
bazel_dep(name = "protobuf", version = "21.7")
"""

        mod_file = parse_MODULE_file_content(module_content_str)

        assert mod_file.version is None
        assert mod_file.comp_level is None
        assert mod_file.raw_content is module_content_str
        mod_file_placeholder_content = """module(
    name = "score_demo",
    version = "",
    compatibility_level = 0
)

bazel_dep(name = "rules_python", version = "0.26.0")
bazel_dep(name = "protobuf", version = "21.7")
"""
        assert mod_file.content == mod_file_placeholder_content

        update_info = make_update_info(version=release_version)
        update_info.mod_file = mod_file

        runner = ModuleUpdateRunner(update_info)
        with patch(
            "src.registry_manager.bazel_wrapper.sha256_from_url",
            return_value="sha256-test",
        ):
            runner.generate_files()

        # Verify patch was created to add version
        patch_file = Path(
            f"/modules/score_demo/{release_version}/patches/module_dot_bazel_version.patch"
        )
        assert patch_file.exists()
        patch_content = patch_file.read_text()
        # We ensure it like this as patch files have other semantics that break out linters
        # So a comparison as multiline string will fail pre-commit linting
        # and has not much human readability as well
        assert patch_content.startswith("""--- a/MODULE.bazel\n+++ b/MODULE.bazel""")

        assert '+    version = "1.5.0",' in patch_content
        assert "+    compatibility_level = 1" in patch_content

        # Make sure it did not touch other things
        assert 'bazel_dep(name = "rules_python", version = "0.26.0")' in patch_content

        module_file = Path(f"/modules/score_demo/{release_version}/MODULE.bazel")
        module_content = module_file.read_text()

        # Ensure that the actual module version was changed
        assert (
            """module(
    name = "score_demo",
    version = "1.5.0",
    compatibility_level = 1
)"""
            in module_content
        )

        # Make sure we did not touch bazel_dep versions
        assert 'bazel_dep(name = "rules_python", version = "0.26.0")' in module_content
        assert 'bazel_dep(name = "protobuf", version = "21.7")' in module_content

    def test_patch_preserves_complex_module_structure(
        self,
        basic_registry_setup: Callable[..., None],
    ) -> None:
        """
        Ensure our patch only touches what it needs to and leaves the rest alone
        """
        basic_registry_setup()
        os.chdir("/")

        release_version = "3.0.0"

        module_content_str = '''
"""
My module documentation
with multiple lines
"""

# Important comment
module(
    name = "score_demo",
    version = "2.5.0",
    compatibility_level = 2,
)

# Core dependencies
bazel_dep(name = "rules_python", version = "0.26.0")
bazel_dep(name = "rules_java", version = "5.3.5")

# Development dependencies
bazel_dep(name = "buildifier_prebuilt", version = "6.1.0", dev_dependency = True)
'''

        mod_file = parse_MODULE_file_content(module_content_str)

        assert str(mod_file.version) == "2.5.0"
        assert mod_file.comp_level == 2

        update_info = make_update_info(version=release_version)
        update_info.mod_file = mod_file

        runner = ModuleUpdateRunner(update_info)
        with patch(
            "src.registry_manager.bazel_wrapper.sha256_from_url",
            return_value="sha256-test",
        ):
            runner.generate_files()

        module_file = Path(f"/modules/score_demo/{release_version}/MODULE.bazel")
        module_content = module_file.read_text()

        # Make sure we only touched the 'module' part
        assert (
            '''
"""
My module documentation
with multiple lines
"""

# Important comment
module(
    name = "score_demo",
    version = "3.0.0",
    compatibility_level = 3,
)

# Core dependencies
bazel_dep(name = "rules_python", version = "0.26.0")
bazel_dep(name = "rules_java", version = "5.3.5")

# Development dependencies
bazel_dep(name = "buildifier_prebuilt", version = "6.1.0", dev_dependency = True)
'''
            in module_content
        )
